In [2]:
import time
import pandas as pd
import numpy as np

CITY_DATA = { 'chicago': 'chicago.csv',
              'new york city': 'new_york_city.csv',
              'washington': 'washington.csv' }


def get_filters():
    print('Hello! Let\'s explore some US bikeshare data!')
    # get user input for city (chicago, new york city, washington). HINT: Use a while loop to handle invalid inputs
    country=['chicago', 'new york city', 'washington']
    city=input("would you like to see data for chicago, new york city, washington").lower()           
    while city not in country:
        print("please choose city from list")
        city=input( ).lower()

    # get user input for month (all, january, february, ... , june)
    months=['all', 'january','february','march','april','may','june']
    print('choose month from list: january,february,march,april,may,june')
    month=input('enter month or all').lower()
    while month not in months:
        print("please choose month from list")
        month=input( ).lower()


    # get user input for day of week (all, monday, tuesday, ... sunday)
    days=['all','sunday','monday','tuesday','wednesday','thursday','friday','saturday']
    print('choose day from list:sunday,monday,tuesday,wednesday,thursday,friday,saturday')
    day=input("enter day or all").lower()
    while day not in days:
        print("please choose day from list")
        day=input( ).lower()
    

    print('-'*40)
    return city, month, day


def load_data(city, month, day):

    df = pd.read_csv(CITY_DATA[city])
    df['Start Time'] = pd.to_datetime(df['Start Time'])
    df['month'] = df['Start Time'].dt.month
    df['day_of_week'] = df['Start Time'].dt.weekday_name
    
    
    if month != 'all':
        months = ['january', 'february', 'march', 'april', 'may', 'june']
        month = months.index(month) + 1
        df = df[df['month'] == month]
        
        
    if day != 'all':
        df = df[df['day_of_week'] == day.title()]
        
        
    #to add new 2 columns in washington (gender and birth year)
    #to deal with func user_stats 
    if city=='washington':
        df['Gender']=np.nan
        df['Birth Year']=np.nan


    return df


def time_stats(df):

    print('\nCalculating The Most Frequent Times of Travel...\n')
    start_time = time.time()

    # display the most common month
    most_month = df['month'].mode()
    print("most common month",most_month)

    # display the most common day of week
    most_day = df['day_of_week'].mode()
    print("most common day",most_day)

    # display the most common start hour
    df['hour'] = df['Start Time'].dt.hour
    popular_hour = df['hour'].mode()[0]
    print("most common time",popular_hour)


    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)


def station_stats(df):
    """Displays statistics on the most popular stations and trip."""

    print('\nCalculating The Most Popular Stations and Trip...\n')
    start_time = time.time()

    # display most commonly used start station
    start_station=df['Start Station'].mode()    
    print("most common start station",start_station)
    

    # display most commonly used end station
    end_station=df['End Station'].mode()
    print("most common end station",end_station)
    

    # display most frequent combination of start station and end station trip
    print("most common combination of start station and end station trip")
    print(df.groupby(['Start Station','End Station']).size().idxmax())
    

    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)


def trip_duration_stats(df):

    print('\nCalculating Trip Duration...\n')
    start_time = time.time()

    # display total travel time
    travel_time=df['Trip Duration'].sum()
    print("the total time",travel_time)
    

    # display mean travel time
    avg_time=df['Trip Duration'].mean()
    print("the avg time ",avg_time)


    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)


def user_stats(df):

    print('\nCalculating User Stats...\n')
    start_time = time.time()

    # Display counts of user types
    user_types = df['User Type'].value_counts()
    print("user type ",user_types)


    # Display counts of gender
    df['Gender']=df['Gender'].fillna(0)
    user_gender = df['Gender'].value_counts()
    print("user gender",user_gender)


    # Display earliest, most recent, and most common year of birth
    
    early=df['Birth Year'].min()
    recent=df['Birth Year'].max()
    most_common=df['Birth Year'].mode()
    print("early year",early)
    print("recent year",recent)
    print("most used year",most_common)


    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)


def display_raw_data(df):
    i=0
    display=input("do you want to see 5 rows of data yes/no").lower()
    answer=["yes","no"]
    while display not in answer:
        print("please write yes or no")
        display=input( ).lower()
    pd.set_option('display.max_columns',200) #but already the columns not more than 200  
    
        
    while True:
        if display=="no" :
            break
        print(df[i:i+5])
        display=input("do you want to see 5 more rows of data yes/no").lower()
        while display not in answer:
            print("please write yes or no")
            display=input( ).lower()
        i+=5
    
    
def main():
    while True:
        city, month, day = get_filters()
        df = load_data(city, month, day)

        time_stats(df)
        station_stats(df)
        trip_duration_stats(df)
        user_stats(df)
        display_raw_data(df)

        restart = input('\nWould you like to restart? Enter yes or no.\n')
        if restart.lower() != 'yes':
            break


if __name__ == "__main__":
	main()

Hello! Let's explore some US bikeshare data!
would you like to see data for chicago, new york city, washingtonchicago
choose month from list: january,february,march,april,may,june
enter month or allmay
choose day from list:sunday,monday,tuesday,wednesday,thursday,friday,saturday
enter day or allmonday
----------------------------------------

Calculating The Most Frequent Times of Travel...

most common month 0    5
dtype: int64
most common day 0    Monday
dtype: object
most common time 17

This took 0.005984783172607422 seconds.
----------------------------------------

Calculating The Most Popular Stations and Trip...

most common start station 0    Streeter Dr & Grand Ave
dtype: object
most common end station 0    Streeter Dr & Grand Ave
dtype: object
most common combination of start station and end station trip
('Lake Shore Dr & Monroe St', 'Streeter Dr & Grand Ave')

This took 0.011968374252319336 seconds.
----------------------------------------

Calculating Trip Duration...

the total time 12697151
the avg time  1051.0886589403974

This took 0.000997781753540039 seconds.
----------------------------------------

Calculating User Stats...

user type  Subscriber    8962
Customer      3118
Name: User Type, dtype: int64
user gender Male      6717
0         3117
Female    2246
Name: Gender, dtype: int64
early year 1906.0
recent year 2001.0
most used year 0    1989.0
dtype: float64

This took 0.008973836898803711 seconds.
----------------------------------------
do you want to see 5 rows of data yes/noyes
    Unnamed: 0          Start Time             End Time  Trip Duration  \
43      915409 2017-05-22 05:49:43  2017-05-22 05:51:15             92
54      702079 2017-05-01 08:35:17  2017-05-01 08:49:02            825
89      763995 2017-05-08 17:29:05  2017-05-08 17:39:32            627
92      760491 2017-05-08 12:00:14  2017-05-08 12:07:23            429
98      919854 2017-05-22 11:44:34  2017-05-22 12:08:13           1419

                 Start Station                  End Station   User Type  \
43    Clark St & Congress Pkwy    LaSalle St & Jackson Blvd  Subscriber
54     Sedgwick St & North Ave        Michigan Ave & Oak St  Subscriber
89  Franklin St & Jackson Blvd    Franklin St & Chicago Ave  Subscriber
92          Clark St & Lake St        Dearborn St & Erie St  Subscriber
98             Montrose Harbor  Lake Shore Dr & Belmont Ave    Customer

   Gender  Birth Year  month day_of_week  hour
43   Male      1967.0      5      Monday     5
54   Male      1983.0      5      Monday     8
89   Male      1975.0      5      Monday    17
92   Male      1963.0      5      Monday    12
98      0         NaN      5      Monday    11
do you want to see 5 more rows of data yes/noyes
     Unnamed: 0          Start Time             End Time  Trip Duration  \
108      918044 2017-05-22 08:50:17  2017-05-22 09:01:09            652
199      835329 2017-05-15 07:40:24  2017-05-15 07:53:34            790
211      702303 2017-05-01 08:46:47  2017-05-01 08:50:49            242
225      918533 2017-05-22 09:25:42  2017-05-22 09:29:15            213
246     1015409 2017-05-29 21:40:46  2017-05-29 21:50:49            603

                   Start Station                   End Station   User Type  \
108  Dearborn Pkwy & Delaware Pl  Clinton St & Washington Blvd  Subscriber
199        Canal St & Madison St     Columbus Dr & Randolph St  Subscriber
211      Clinton St & Madison St   Desplaines St & Randolph St  Subscriber
225      Paulina Ave & North Ave     Ashland Ave & Division St  Subscriber
246       Michigan Ave & 14th St               McCormick Place  Subscriber

     Gender  Birth Year  month day_of_week  hour
108    Male      1987.0      5      Monday     8
199    Male      1968.0      5      Monday     7
211    Male      1967.0      5      Monday     8
225    Male      1969.0      5      Monday     9
246  Female      1991.0      5      Monday    21
do you want to see 5 more rows of data yes/nono

Would you like to restart? Enter yes or no.
yes
Hello! Let's explore some US bikeshare data!
would you like to see data for chicago, new york city, washingtonnew york city
choose month from list: january,february,march,april,may,june
enter month or allapril
choose day from list:sunday,monday,tuesday,wednesday,thursday,friday,saturday
enter day or allsunday
----------------------------------------

Calculating The Most Frequent Times of Travel...

most common month 0    4
dtype: int64
most common day 0    Sunday
dtype: object
most common time 14

This took 0.00498652458190918 seconds.
----------------------------------------

Calculating The Most Popular Stations and Trip...

most common start station 0    Central Park S & 6 Ave
dtype: object
most common end station 0    Central Park S & 6 Ave
dtype: object
most common combination of start station and end station trip
('Central Park S & 6 Ave', 'Central Park S & 6 Ave')

This took 0.009972572326660156 seconds.
----------------------------------------

Calculating Trip Duration...

the total time 11082843
the avg time  1121.7452429149798

This took 0.000997781753540039 seconds.
----------------------------------------

Calculating User Stats...

user type  Subscriber    7313
Customer      2567
Name: User Type, dtype: int64
user gender Male      5274
0         2360
Female    2246
Name: Gender, dtype: int64
early year 1885.0
recent year 2001.0
most used year 0    1989.0
dtype: float64

This took 0.005984067916870117 seconds.
----------------------------------------
do you want to see 5 rows of data yes/noyes
     Unnamed: 0          Start Time             End Time  Trip Duration  \
8       2271331 2017-04-02 08:02:36  2017-04-02 09:28:08           5132
10      2287178 2017-04-02 14:37:20  2017-04-02 14:56:12           1131
24      2905932 2017-04-16 17:36:06  2017-04-16 18:02:52           1605
52      2897347 2017-04-16 15:23:43  2017-04-16 15:44:16           1233
125     2561325 2017-04-09 20:20:13  2017-04-09 20:30:02            588

                Start Station             End Station   User Type Gender  \
8      Central Park S & 6 Ave  Central Park S & 6 Ave    Customer      0
10    Bank St & Washington St   Little West St & 1 Pl    Customer      0
24      Allen St & Stanton St     Mott St & Prince St  Subscriber   Male
52   Cleveland Pl & Spring St         S 5 Pl & S 4 St    Customer      0
125           2 Ave & E 31 St      E 17 St & Broadway  Subscriber   Male

     Birth Year  month day_of_week  hour
8           NaN      4      Sunday     8
10          NaN      4      Sunday    14
24       1983.0      4      Sunday    17
52          NaN      4      Sunday    15
125      1993.0      4      Sunday    20
do you want to see 5 more rows of data yes/nono

Would you like to restart? Enter yes or no.
yes
Hello! Let's explore some US bikeshare data!
would you like to see data for chicago, new york city, washingtonwashington
choose month from list: january,february,march,april,may,june
enter month or allmarch
choose day from list:sunday,monday,tuesday,wednesday,thursday,friday,saturday
enter day or allsaturday
----------------------------------------

Calculating The Most Frequent Times of Travel...

most common month 0    3
dtype: int64
most common day 0    Saturday
dtype: object
most common time 14

This took 0.0039899349212646484 seconds.
----------------------------------------

Calculating The Most Popular Stations and Trip...

most common start station 0    Jefferson Dr & 14th St SW
dtype: object
most common end station 0    Jefferson Dr & 14th St SW
dtype: object
most common combination of start station and end station trip
('Jefferson Memorial', 'Jefferson Memorial')

This took 0.008975982666015625 seconds.
----------------------------------------

Calculating Trip Duration...

the total time 10276953.973000001
the avg time  1728.962646870789

This took 0.0009968280792236328 seconds.
----------------------------------------

Calculating User Stats...

user type  Subscriber    3300
Customer      2644
Name: User Type, dtype: int64
user gender 0.0    5944
Name: Gender, dtype: int64
early year nan
recent year nan
most used year Series([], dtype: float64)

This took 0.00598454475402832 seconds.
----------------------------------------

do you want to see 5 rows of data yes/noyes
     Unnamed: 0          Start Time             End Time  Trip Duration  \
1        482740 2017-03-11 10:40:00  2017-03-11 10:46:00        402.549
38       582231 2017-03-25 14:16:00  2017-03-25 14:35:00       1127.911
71       590016 2017-03-25 20:42:00  2017-03-25 21:18:00       2171.291
285      521787 2017-03-18 17:27:00  2017-03-18 17:30:00        201.276
305      429803 2017-03-04 20:27:00  2017-03-04 20:37:00        591.502

                                         Start Station  \
1                           Yuma St & Tenley Circle NW
38                                      18th & R St NW
71   Smithsonian-National Mall / Jefferson Dr & 12t...
285                                     15th & P St NW
305                          New York Ave & 15th St NW

                      End Station   User Type  month day_of_week  Gender  \
1    Connecticut Ave & Yuma St NW  Subscriber      3    Saturday     0.0
38                  8th & D St NW  Subscriber      3    Saturday     0.0
71                  3rd & D St SE    Customer      3    Saturday     0.0
285    17th & Rhode Island Ave NW  Subscriber      3    Saturday     0.0
305                15th & P St NW  Subscriber      3    Saturday     0.0

     Birth Year  hour
1           NaN    10
38          NaN    14
71          NaN    20
285         NaN    17
305         NaN    20
do you want to see 5 more rows of data yes/nono

Would you like to restart? Enter yes or no.
no